const menuItems = [
    {
        id: 1,
        image: "/images/coffee9.jpeg",
        heading: "Tasty and Healthy",
        price: "₹1199",
        inr: "₹1299",
        btn: "Add to Cart",
    },
    {
        id: 2,
        image: "/images/coffee5.jpeg",
        heading: "Tasty and Healthy",
        price: "₹1199",
        inr: "₹1299",
        btn: "Add to Cart",
    },
    {
        id: 3,
        image: "/images/coffee9.jpeg",
        heading: "Tasty and Healthy",
        price: "₹1199",
        inr: "₹1299",
        btn: "Add to Cart",
    },
    {
        id: 4,
        image: "/images/coffee9.jpeg",
        heading: "Tasty and Healthy",
        price: "₹1199",
        inr: "₹1299",
        btn: "Add to Cart",
    },
    {
        id: 5,
        image: "/images/coffee9.jpeg",
        heading: "Tasty and Healthy",
        price: "₹1199",
        inr: "₹1299",
        btn: "Add to Cart",
    },
    {
        id: 6,
        image: "/images/coffee9.jpeg",
        heading: "Tasty and Healthy",
        price: "₹1199",
        inr: "₹1299",
        btn: "Add to Cart",
    },
    {
        id: 7,
        image: "/images/coffee9.jpeg",
        heading: "Tasty and Healthy",
        price: "$1199",
        inr: "₹1299",
        btn: "Add to Cart",
    },
    {
        id: 8,
        image: "/images/coffee9.jpeg",
        heading: "Tasty and Healthy",
        price: "$1199",
        inr: "₹1299",
        btn: "Add to Cart",
    },
];

export default menuItems;